/* Auto-generated by genmsg_cpp for file /home/emi/work_electric/pmd_camcube_3/pmd_camcube_3_ros_pkg/msg/Distance.msg */
#ifndef PMD_CAMCUBE_3_ROS_PKG_MESSAGE_DISTANCE_H
#define PMD_CAMCUBE_3_ROS_PKG_MESSAGE_DISTANCE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace pmd_camcube_3_ros_pkg
{
template <class ContainerAllocator>
struct Distance_ {
  typedef Distance_<ContainerAllocator> Type;

  Distance_()
  : Distances()
  {
  }

  Distance_(const ContainerAllocator& _alloc)
  : Distances(_alloc)
  {
  }

  typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _Distances_type;
  std::vector<float, typename ContainerAllocator::template rebind<float>::other >  Distances;


  ROS_DEPRECATED uint32_t get_Distances_size() const { return (uint32_t)Distances.size(); }
  ROS_DEPRECATED void set_Distances_size(uint32_t size) { Distances.resize((size_t)size); }
  ROS_DEPRECATED void get_Distances_vec(std::vector<float, typename ContainerAllocator::template rebind<float>::other > & vec) const { vec = this->Distances; }
  ROS_DEPRECATED void set_Distances_vec(const std::vector<float, typename ContainerAllocator::template rebind<float>::other > & vec) { this->Distances = vec; }
private:
  static const char* __s_getDataType_() { return "pmd_camcube_3_ros_pkg/Distance"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "b7c0d0f9565f53d3ad5c0e99ce58dd26"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "float32[] Distances\n\
\n\
\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, Distances);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, Distances);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(Distances);
    return size;
  }

  typedef boost::shared_ptr< ::pmd_camcube_3_ros_pkg::Distance_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pmd_camcube_3_ros_pkg::Distance_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Distance
typedef  ::pmd_camcube_3_ros_pkg::Distance_<std::allocator<void> > Distance;

typedef boost::shared_ptr< ::pmd_camcube_3_ros_pkg::Distance> DistancePtr;
typedef boost::shared_ptr< ::pmd_camcube_3_ros_pkg::Distance const> DistanceConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::pmd_camcube_3_ros_pkg::Distance_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::pmd_camcube_3_ros_pkg::Distance_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace pmd_camcube_3_ros_pkg

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::pmd_camcube_3_ros_pkg::Distance_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::pmd_camcube_3_ros_pkg::Distance_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::pmd_camcube_3_ros_pkg::Distance_<ContainerAllocator> > {
  static const char* value() 
  {
    return "b7c0d0f9565f53d3ad5c0e99ce58dd26";
  }

  static const char* value(const  ::pmd_camcube_3_ros_pkg::Distance_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xb7c0d0f9565f53d3ULL;
  static const uint64_t static_value2 = 0xad5c0e99ce58dd26ULL;
};

template<class ContainerAllocator>
struct DataType< ::pmd_camcube_3_ros_pkg::Distance_<ContainerAllocator> > {
  static const char* value() 
  {
    return "pmd_camcube_3_ros_pkg/Distance";
  }

  static const char* value(const  ::pmd_camcube_3_ros_pkg::Distance_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::pmd_camcube_3_ros_pkg::Distance_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float32[] Distances\n\
\n\
\n\
\n\
";
  }

  static const char* value(const  ::pmd_camcube_3_ros_pkg::Distance_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::pmd_camcube_3_ros_pkg::Distance_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.Distances);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Distance_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pmd_camcube_3_ros_pkg::Distance_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::pmd_camcube_3_ros_pkg::Distance_<ContainerAllocator> & v) 
  {
    s << indent << "Distances[]" << std::endl;
    for (size_t i = 0; i < v.Distances.size(); ++i)
    {
      s << indent << "  Distances[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.Distances[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // PMD_CAMCUBE_3_ROS_PKG_MESSAGE_DISTANCE_H

