/* Auto-generated by genmsg_cpp for file /home/emi/work_electric/pmd_camcube_3/pmd_camcube_3_ros_pkg/msg/Pixels.msg */
#ifndef PMD_CAMCUBE_3_ROS_PKG_MESSAGE_PIXELS_H
#define PMD_CAMCUBE_3_ROS_PKG_MESSAGE_PIXELS_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace pmd_camcube_3_ros_pkg
{
template <class ContainerAllocator>
struct Pixels_ {
  typedef Pixels_<ContainerAllocator> Type;

  Pixels_()
  : Pixels()
  , maxDist(0.0)
  , maxPixel(0)
  , width(0)
  , height(0)
  {
  }

  Pixels_(const ContainerAllocator& _alloc)
  : Pixels(_alloc)
  , maxDist(0.0)
  , maxPixel(0)
  , width(0)
  , height(0)
  {
  }

  typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _Pixels_type;
  std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  Pixels;

  typedef float _maxDist_type;
  float maxDist;

  typedef uint8_t _maxPixel_type;
  uint8_t maxPixel;

  typedef uint8_t _width_type;
  uint8_t width;

  typedef uint8_t _height_type;
  uint8_t height;


  ROS_DEPRECATED uint32_t get_Pixels_size() const { return (uint32_t)Pixels.size(); }
  ROS_DEPRECATED void set_Pixels_size(uint32_t size) { Pixels.resize((size_t)size); }
  ROS_DEPRECATED void get_Pixels_vec(std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other > & vec) const { vec = this->Pixels; }
  ROS_DEPRECATED void set_Pixels_vec(const std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other > & vec) { this->Pixels = vec; }
private:
  static const char* __s_getDataType_() { return "pmd_camcube_3_ros_pkg/Pixels"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "25405a9889a230a21c04df203440f575"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "uint8[] Pixels\n\
float32 maxDist\n\
uint8 maxPixel\n\
uint8 width\n\
uint8 height\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, Pixels);
    ros::serialization::serialize(stream, maxDist);
    ros::serialization::serialize(stream, maxPixel);
    ros::serialization::serialize(stream, width);
    ros::serialization::serialize(stream, height);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, Pixels);
    ros::serialization::deserialize(stream, maxDist);
    ros::serialization::deserialize(stream, maxPixel);
    ros::serialization::deserialize(stream, width);
    ros::serialization::deserialize(stream, height);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(Pixels);
    size += ros::serialization::serializationLength(maxDist);
    size += ros::serialization::serializationLength(maxPixel);
    size += ros::serialization::serializationLength(width);
    size += ros::serialization::serializationLength(height);
    return size;
  }

  typedef boost::shared_ptr< ::pmd_camcube_3_ros_pkg::Pixels_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pmd_camcube_3_ros_pkg::Pixels_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Pixels
typedef  ::pmd_camcube_3_ros_pkg::Pixels_<std::allocator<void> > Pixels;

typedef boost::shared_ptr< ::pmd_camcube_3_ros_pkg::Pixels> PixelsPtr;
typedef boost::shared_ptr< ::pmd_camcube_3_ros_pkg::Pixels const> PixelsConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::pmd_camcube_3_ros_pkg::Pixels_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::pmd_camcube_3_ros_pkg::Pixels_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace pmd_camcube_3_ros_pkg

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::pmd_camcube_3_ros_pkg::Pixels_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::pmd_camcube_3_ros_pkg::Pixels_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::pmd_camcube_3_ros_pkg::Pixels_<ContainerAllocator> > {
  static const char* value() 
  {
    return "25405a9889a230a21c04df203440f575";
  }

  static const char* value(const  ::pmd_camcube_3_ros_pkg::Pixels_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x25405a9889a230a2ULL;
  static const uint64_t static_value2 = 0x1c04df203440f575ULL;
};

template<class ContainerAllocator>
struct DataType< ::pmd_camcube_3_ros_pkg::Pixels_<ContainerAllocator> > {
  static const char* value() 
  {
    return "pmd_camcube_3_ros_pkg/Pixels";
  }

  static const char* value(const  ::pmd_camcube_3_ros_pkg::Pixels_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::pmd_camcube_3_ros_pkg::Pixels_<ContainerAllocator> > {
  static const char* value() 
  {
    return "uint8[] Pixels\n\
float32 maxDist\n\
uint8 maxPixel\n\
uint8 width\n\
uint8 height\n\
\n\
";
  }

  static const char* value(const  ::pmd_camcube_3_ros_pkg::Pixels_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::pmd_camcube_3_ros_pkg::Pixels_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.Pixels);
    stream.next(m.maxDist);
    stream.next(m.maxPixel);
    stream.next(m.width);
    stream.next(m.height);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Pixels_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pmd_camcube_3_ros_pkg::Pixels_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::pmd_camcube_3_ros_pkg::Pixels_<ContainerAllocator> & v) 
  {
    s << indent << "Pixels[]" << std::endl;
    for (size_t i = 0; i < v.Pixels.size(); ++i)
    {
      s << indent << "  Pixels[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.Pixels[i]);
    }
    s << indent << "maxDist: ";
    Printer<float>::stream(s, indent + "  ", v.maxDist);
    s << indent << "maxPixel: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.maxPixel);
    s << indent << "width: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.width);
    s << indent << "height: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.height);
  }
};


} // namespace message_operations
} // namespace ros

#endif // PMD_CAMCUBE_3_ROS_PKG_MESSAGE_PIXELS_H

