//#line 2 "/opt/ros/electric/stacks/driver_common/dynamic_reconfigure/templates/ConfigType.h"
// *********************************************************
// 
// File autogenerated for the pmd_camcube_3_ros_pkg package 
// by the dynamic_reconfigure package.
// Please do not edit.
// 
// ********************************************************/

/***********************************************************
 * Software License Agreement (BSD License)
 *
 *  Copyright (c) 2008, Willow Garage, Inc.
 *  All rights reserved.
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *   * Redistributions of source code must retain the above copyright
 *     notice, this list of conditions and the following disclaimer.
 *   * Redistributions in binary form must reproduce the above
 *     copyright notice, this list of conditions and the following
 *     disclaimer in the documentation and/or other materials provided
 *     with the distribution.
 *   * Neither the name of the Willow Garage nor the names of its
 *     contributors may be used to endorse or promote products derived
 *     from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 *  FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 *  COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 *  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 *  BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 *  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 *  CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 *  LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 *  ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 *  POSSIBILITY OF SUCH DAMAGE.
 ***********************************************************/

// Author: Blaise Gassend


#ifndef __pmd_camcube_3_ros_pkg__PMD_CAMCUBE_3_ROS_PKGCONFIG_H__
#define __pmd_camcube_3_ros_pkg__PMD_CAMCUBE_3_ROS_PKGCONFIG_H__

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/config_init_mutex.h>

namespace pmd_camcube_3_ros_pkg
{
  class pmd_camcube_3_ros_pkgConfigStatics;
  
  class pmd_camcube_3_ros_pkgConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l, 
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      
      virtual void clamp(pmd_camcube_3_ros_pkgConfig &config, const pmd_camcube_3_ros_pkgConfig &max, const pmd_camcube_3_ros_pkgConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const pmd_camcube_3_ros_pkgConfig &config1, const pmd_camcube_3_ros_pkgConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, pmd_camcube_3_ros_pkgConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const pmd_camcube_3_ros_pkgConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, pmd_camcube_3_ros_pkgConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const pmd_camcube_3_ros_pkgConfig &config) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;
    
    template <class T>
    class ParamDescription : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string name, std::string type, uint32_t level, 
          std::string description, std::string edit_method, T pmd_camcube_3_ros_pkgConfig::* f) :
        AbstractParamDescription(name, type, level, description, edit_method),
        field(f)
      {}

      T (pmd_camcube_3_ros_pkgConfig::* field);

      virtual void clamp(pmd_camcube_3_ros_pkgConfig &config, const pmd_camcube_3_ros_pkgConfig &max, const pmd_camcube_3_ros_pkgConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;
        
        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const pmd_camcube_3_ros_pkgConfig &config1, const pmd_camcube_3_ros_pkgConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, pmd_camcube_3_ros_pkgConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const pmd_camcube_3_ros_pkgConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, pmd_camcube_3_ros_pkgConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const pmd_camcube_3_ros_pkgConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }
    };

//#line 17 "../cfg/pmd_camcube_3.cfg"
      int Integration_Time;
//#line 19 "../cfg/pmd_camcube_3.cfg"
      int Modulation_Frequency;
//#line 20 "../cfg/pmd_camcube_3.cfg"
      bool At_Least;
//#line 21 "../cfg/pmd_camcube_3.cfg"
      bool At_Most;
//#line 23 "../cfg/pmd_camcube_3.cfg"
      bool Statistical_Noise_Filter_On;
//#line 24 "../cfg/pmd_camcube_3.cfg"
      int Noise_Filtering_NoOfNeighbours;
//#line 25 "../cfg/pmd_camcube_3.cfg"
      double Std_Dev_Mul_Threshold;
//#line 27 "../cfg/pmd_camcube_3.cfg"
      bool Amplitude_Filter_On;
//#line 28 "../cfg/pmd_camcube_3.cfg"
      double Amplitude_Threshold;
//#line 138 "/opt/ros/electric/stacks/driver_common/dynamic_reconfigure/templates/ConfigType.h"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        if ((*i)->fromMessage(msg, *this))
          count++;
      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("pmd_camcube_3_ros_pkgConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->toMessage(msg, *this);
    }
    
    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      __toMessage__(msg, __param_descriptions__);
    }
    
    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->fromServer(nh, *this);
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const pmd_camcube_3_ros_pkgConfig &__max__ = __getMax__();
      const pmd_camcube_3_ros_pkgConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const pmd_camcube_3_ros_pkgConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->calcLevel(level, config, *this);
      return level;
    }
    
    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const pmd_camcube_3_ros_pkgConfig &__getDefault__();
    static const pmd_camcube_3_ros_pkgConfig &__getMax__();
    static const pmd_camcube_3_ros_pkgConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    
  private:
    static const pmd_camcube_3_ros_pkgConfigStatics *__get_statics__();
  };
  
  template <> // Max and min are ignored for strings.
  inline void pmd_camcube_3_ros_pkgConfig::ParamDescription<std::string>::clamp(pmd_camcube_3_ros_pkgConfig &config, const pmd_camcube_3_ros_pkgConfig &max, const pmd_camcube_3_ros_pkgConfig &min) const
  {
    return;
  }

  class pmd_camcube_3_ros_pkgConfigStatics
  {
    friend class pmd_camcube_3_ros_pkgConfig;
    
    pmd_camcube_3_ros_pkgConfigStatics()
    {
//#line 17 "../cfg/pmd_camcube_3.cfg"
      __min__.Integration_Time = 238;
//#line 17 "../cfg/pmd_camcube_3.cfg"
      __max__.Integration_Time = 5000;
//#line 17 "../cfg/pmd_camcube_3.cfg"
      __default__.Integration_Time = 250;
//#line 17 "../cfg/pmd_camcube_3.cfg"
      __param_descriptions__.push_back(pmd_camcube_3_ros_pkgConfig::AbstractParamDescriptionConstPtr(new pmd_camcube_3_ros_pkgConfig::ParamDescription<int>("Integration_Time", "int", 0, "Integration time(in msec) for the sensor", "", &pmd_camcube_3_ros_pkgConfig::Integration_Time)));
//#line 19 "../cfg/pmd_camcube_3.cfg"
      __min__.Modulation_Frequency = 18000000;
//#line 19 "../cfg/pmd_camcube_3.cfg"
      __max__.Modulation_Frequency = 23000000;
//#line 19 "../cfg/pmd_camcube_3.cfg"
      __default__.Modulation_Frequency = 20000000;
//#line 19 "../cfg/pmd_camcube_3.cfg"
      __param_descriptions__.push_back(pmd_camcube_3_ros_pkgConfig::AbstractParamDescriptionConstPtr(new pmd_camcube_3_ros_pkgConfig::ParamDescription<int>("Modulation_Frequency", "int", 0, "Set the modulation frequency(Hz) of the sensor. By Default the frequency closest to the given value will be set.", "", &pmd_camcube_3_ros_pkgConfig::Modulation_Frequency)));
//#line 20 "../cfg/pmd_camcube_3.cfg"
      __min__.At_Least = 0;
//#line 20 "../cfg/pmd_camcube_3.cfg"
      __max__.At_Least = 1;
//#line 20 "../cfg/pmd_camcube_3.cfg"
      __default__.At_Least = 0;
//#line 20 "../cfg/pmd_camcube_3.cfg"
      __param_descriptions__.push_back(pmd_camcube_3_ros_pkgConfig::AbstractParamDescriptionConstPtr(new pmd_camcube_3_ros_pkgConfig::ParamDescription<bool>("At_Least", "bool", 0, "Modulation Frequency no less than the entered frequency will be set", "", &pmd_camcube_3_ros_pkgConfig::At_Least)));
//#line 21 "../cfg/pmd_camcube_3.cfg"
      __min__.At_Most = 0;
//#line 21 "../cfg/pmd_camcube_3.cfg"
      __max__.At_Most = 1;
//#line 21 "../cfg/pmd_camcube_3.cfg"
      __default__.At_Most = 0;
//#line 21 "../cfg/pmd_camcube_3.cfg"
      __param_descriptions__.push_back(pmd_camcube_3_ros_pkgConfig::AbstractParamDescriptionConstPtr(new pmd_camcube_3_ros_pkgConfig::ParamDescription<bool>("At_Most", "bool", 0, "Modulation Frequency no more than the entered frequency will be set", "", &pmd_camcube_3_ros_pkgConfig::At_Most)));
//#line 23 "../cfg/pmd_camcube_3.cfg"
      __min__.Statistical_Noise_Filter_On = 0;
//#line 23 "../cfg/pmd_camcube_3.cfg"
      __max__.Statistical_Noise_Filter_On = 1;
//#line 23 "../cfg/pmd_camcube_3.cfg"
      __default__.Statistical_Noise_Filter_On = 0;
//#line 23 "../cfg/pmd_camcube_3.cfg"
      __param_descriptions__.push_back(pmd_camcube_3_ros_pkgConfig::AbstractParamDescriptionConstPtr(new pmd_camcube_3_ros_pkgConfig::ParamDescription<bool>("Statistical_Noise_Filter_On", "bool", 0, "Whether to apply statistical noise filter from pcl or not.", "", &pmd_camcube_3_ros_pkgConfig::Statistical_Noise_Filter_On)));
//#line 24 "../cfg/pmd_camcube_3.cfg"
      __min__.Noise_Filtering_NoOfNeighbours = 1;
//#line 24 "../cfg/pmd_camcube_3.cfg"
      __max__.Noise_Filtering_NoOfNeighbours = 200;
//#line 24 "../cfg/pmd_camcube_3.cfg"
      __default__.Noise_Filtering_NoOfNeighbours = 30;
//#line 24 "../cfg/pmd_camcube_3.cfg"
      __param_descriptions__.push_back(pmd_camcube_3_ros_pkgConfig::AbstractParamDescriptionConstPtr(new pmd_camcube_3_ros_pkgConfig::ParamDescription<int>("Noise_Filtering_NoOfNeighbours", "int", 0, "No of neighbours to be considered for applying statistical noise reduction", "", &pmd_camcube_3_ros_pkgConfig::Noise_Filtering_NoOfNeighbours)));
//#line 25 "../cfg/pmd_camcube_3.cfg"
      __min__.Std_Dev_Mul_Threshold = 0.0;
//#line 25 "../cfg/pmd_camcube_3.cfg"
      __max__.Std_Dev_Mul_Threshold = 10.0;
//#line 25 "../cfg/pmd_camcube_3.cfg"
      __default__.Std_Dev_Mul_Threshold = 0.4;
//#line 25 "../cfg/pmd_camcube_3.cfg"
      __param_descriptions__.push_back(pmd_camcube_3_ros_pkgConfig::AbstractParamDescriptionConstPtr(new pmd_camcube_3_ros_pkgConfig::ParamDescription<double>("Std_Dev_Mul_Threshold", "double", 0, "Standard Deviation Multiplier Threshold for applying statistical noise reduction", "", &pmd_camcube_3_ros_pkgConfig::Std_Dev_Mul_Threshold)));
//#line 27 "../cfg/pmd_camcube_3.cfg"
      __min__.Amplitude_Filter_On = 0;
//#line 27 "../cfg/pmd_camcube_3.cfg"
      __max__.Amplitude_Filter_On = 1;
//#line 27 "../cfg/pmd_camcube_3.cfg"
      __default__.Amplitude_Filter_On = 0;
//#line 27 "../cfg/pmd_camcube_3.cfg"
      __param_descriptions__.push_back(pmd_camcube_3_ros_pkgConfig::AbstractParamDescriptionConstPtr(new pmd_camcube_3_ros_pkgConfig::ParamDescription<bool>("Amplitude_Filter_On", "bool", 0, "Whether to apply amplitude filter or not. Image pixels with amplitude values less than the threshold will be filtered out", "", &pmd_camcube_3_ros_pkgConfig::Amplitude_Filter_On)));
//#line 28 "../cfg/pmd_camcube_3.cfg"
      __min__.Amplitude_Threshold = 0.0;
//#line 28 "../cfg/pmd_camcube_3.cfg"
      __max__.Amplitude_Threshold = 2500.0;
//#line 28 "../cfg/pmd_camcube_3.cfg"
      __default__.Amplitude_Threshold = 0.0;
//#line 28 "../cfg/pmd_camcube_3.cfg"
      __param_descriptions__.push_back(pmd_camcube_3_ros_pkgConfig::AbstractParamDescriptionConstPtr(new pmd_camcube_3_ros_pkgConfig::ParamDescription<double>("Amplitude_Threshold", "double", 0, "What should be the amplitude filter threshold. Image pixels with lesser aplitude values will be filtered out. Amplitude Filter Status should be true to use this filter.", "", &pmd_camcube_3_ros_pkgConfig::Amplitude_Threshold)));
//#line 239 "/opt/ros/electric/stacks/driver_common/dynamic_reconfigure/templates/ConfigType.h"
    
      for (std::vector<pmd_camcube_3_ros_pkgConfig::AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        __description_message__.parameters.push_back(**i);
      __max__.__toMessage__(__description_message__.max, __param_descriptions__); 
      __min__.__toMessage__(__description_message__.min, __param_descriptions__); 
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__); 
    }
    std::vector<pmd_camcube_3_ros_pkgConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    pmd_camcube_3_ros_pkgConfig __max__;
    pmd_camcube_3_ros_pkgConfig __min__;
    pmd_camcube_3_ros_pkgConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;
    static const pmd_camcube_3_ros_pkgConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static pmd_camcube_3_ros_pkgConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &pmd_camcube_3_ros_pkgConfig::__getDescriptionMessage__() 
  {
    return __get_statics__()->__description_message__;
  }

  inline const pmd_camcube_3_ros_pkgConfig &pmd_camcube_3_ros_pkgConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }
  
  inline const pmd_camcube_3_ros_pkgConfig &pmd_camcube_3_ros_pkgConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }
  
  inline const pmd_camcube_3_ros_pkgConfig &pmd_camcube_3_ros_pkgConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }
  
  inline const std::vector<pmd_camcube_3_ros_pkgConfig::AbstractParamDescriptionConstPtr> &pmd_camcube_3_ros_pkgConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const pmd_camcube_3_ros_pkgConfigStatics *pmd_camcube_3_ros_pkgConfig::__get_statics__()
  {
    const static pmd_camcube_3_ros_pkgConfigStatics *statics;
  
    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = pmd_camcube_3_ros_pkgConfigStatics::get_instance();
    
    return statics;
  }


}

#endif // __PMD_CAMCUBE_3_ROS_PKGRECONFIGURATOR_H__
